import type { RnqCriterionSeed, RnqIndicatorSeed } from "./types";

export const DEFAULT_RNQ_CRITERIA: RnqCriterionSeed[] = [
  {
    number: 1,
    title: "Information des publics",
    description:
      "L'organisme rend accessibles les informations utiles sur ses prestations, leurs conditions d'accès, leurs objectifs et leurs résultats.",
  },
  {
    number: 2,
    title: "Objectifs et adaptation des prestations",
    description:
      "L'organisme identifie les objectifs, analyse les besoins et adapte les prestations aux bénéficiaires et aux financeurs.",
  },
  {
    number: 3,
    title: "Accompagnement et évaluation des bénéficiaires",
    description:
      "L'organisme accompagne les publics, suit leur progression et évalue l'atteinte des objectifs tout au long du parcours.",
  },
  {
    number: 4,
    title: "Moyens pédagogiques, techniques et d'encadrement",
    description:
      "L'organisme mobilise des moyens adaptés, coordonne les intervenants et met à disposition des ressources pertinentes.",
  },
  {
    number: 5,
    title: "Qualification et développement des compétences",
    description:
      "L'organisme s'assure des compétences des intervenants et maintient leur développement professionnel.",
  },
  {
    number: 6,
    title: "Inscription dans l'environnement professionnel",
    description:
      "L'organisme assure une veille utile, prend en compte le handicap, maîtrise la sous-traitance et s'inscrit dans son environnement.",
  },
  {
    number: 7,
    title: "Appréciations et amélioration continue",
    description:
      "L'organisme recueille les retours, traite les difficultés et pilote les actions d'amélioration continue.",
  },
];

export const DEFAULT_RNQ_INDICATORS: RnqIndicatorSeed[] = [
  {
    number: 1,
    criterionNumber: 1,
    title: "Information accessible sur les prestations",
    shortDescription: "Publier une information claire sur les prestations, délais, tarifs, contacts et modalités.",
    expectedLevel: "Les informations utiles sont datées, accessibles et cohérentes avec les prestations proposées.",
    evidenceExamples: ["Page programme publiée", "Brochure commerciale", "Capture de site datée"],
    applicableTo: ["training actions", "apprenticeship", "VAE", "skills assessment"],
    riskLevel: "HIGH",
  },
  {
    number: 2,
    criterionNumber: 1,
    title: "Objectifs et résultats des prestations",
    shortDescription: "Informer sur les objectifs, prérequis, durées, modalités d'évaluation et résultats disponibles.",
    expectedLevel: "Chaque prestation présente des objectifs évaluables et des indicateurs de résultats à jour.",
    evidenceExamples: ["Programme de formation", "Tableau d'indicateurs", "Fiche CPF ou catalogue"],
    applicableTo: ["training actions", "apprenticeship", "VAE", "skills assessment"],
    riskLevel: "HIGH",
  },
  {
    number: 3,
    criterionNumber: 1,
    title: "Taux et résultats de certification",
    shortDescription: "Présenter les taux d'obtention ou résultats lorsque la prestation mène à une certification.",
    expectedLevel: "Les résultats disponibles sont publiés avec une méthode de calcul vérifiable.",
    evidenceExamples: ["Tableau de taux de réussite", "Bilan annuel", "Capture d'information publique"],
    applicableTo: ["training actions", "apprenticeship"],
    riskLevel: "MEDIUM",
  },
  {
    number: 4,
    criterionNumber: 2,
    title: "Analyse du besoin bénéficiaire",
    shortDescription: "Recueillir et analyser les besoins avant l'entrée en prestation.",
    expectedLevel: "Un diagnostic ou entretien d'entrée permet d'adapter le parcours à la situation du bénéficiaire.",
    evidenceExamples: ["Questionnaire d'entrée", "Compte rendu d'entretien", "Fiche de positionnement"],
    applicableTo: ["training actions", "apprenticeship", "VAE", "skills assessment"],
    riskLevel: "CRITICAL",
  },
  {
    number: 5,
    criterionNumber: 2,
    title: "Objectifs opérationnels évaluables",
    shortDescription: "Définir des objectifs mesurables et adaptés aux besoins identifiés.",
    expectedLevel: "Les objectifs sont formulés de manière opérationnelle et reliés aux modalités d'évaluation.",
    evidenceExamples: ["Programme détaillé", "Convention", "Référentiel de compétences"],
    applicableTo: ["training actions", "apprenticeship", "VAE", "skills assessment"],
    riskLevel: "HIGH",
  },
  {
    number: 6,
    criterionNumber: 2,
    title: "Adaptation du parcours",
    shortDescription: "Adapter les contenus, rythmes, moyens ou accompagnements selon le public.",
    expectedLevel: "Les adaptations décidées sont tracées et justifiées selon les situations rencontrées.",
    evidenceExamples: ["Plan individuel", "Compte rendu d'adaptation", "Échanges avec bénéficiaire"],
    applicableTo: ["training actions", "apprenticeship", "VAE", "skills assessment"],
    riskLevel: "HIGH",
  },
  {
    number: 7,
    criterionNumber: 2,
    title: "Adéquation aux exigences de certification",
    shortDescription: "Aligner les prestations certifiantes avec les exigences du certificateur.",
    expectedLevel: "Le contenu, l'évaluation et les prérequis sont cohérents avec la certification visée.",
    evidenceExamples: ["Référentiel certificateur", "Matrice objectifs-épreuves", "Programme certifiant"],
    applicableTo: ["training actions", "apprenticeship"],
    riskLevel: "HIGH",
  },
  {
    number: 8,
    criterionNumber: 2,
    title: "Positionnement à l'entrée",
    shortDescription: "Réaliser un positionnement lorsque nécessaire avant le démarrage.",
    expectedLevel: "Le niveau initial est identifié et utilisé pour ajuster le parcours.",
    evidenceExamples: ["Test de positionnement", "Grille d'entretien", "Diagnostic initial"],
    applicableTo: ["training actions", "apprenticeship", "VAE", "skills assessment"],
    riskLevel: "MEDIUM",
  },
  {
    number: 9,
    criterionNumber: 3,
    title: "Conditions de déroulement",
    shortDescription: "Informer les bénéficiaires sur le déroulement, les contacts et les règles applicables.",
    expectedLevel: "Les bénéficiaires disposent des informations pratiques nécessaires avant et pendant la prestation.",
    evidenceExamples: ["Livret d'accueil", "Convocation", "Règlement intérieur"],
    applicableTo: ["training actions", "apprenticeship", "VAE", "skills assessment"],
    riskLevel: "HIGH",
  },
  {
    number: 10,
    criterionNumber: 3,
    title: "Adaptation de la prestation en cours",
    shortDescription: "Suivre la progression et ajuster l'accompagnement si besoin.",
    expectedLevel: "Les difficultés et adaptations en cours de parcours sont repérées, décidées et tracées.",
    evidenceExamples: ["Feuille de suivi", "Compte rendu pédagogique", "Plan d'accompagnement"],
    applicableTo: ["training actions", "apprenticeship", "VAE", "skills assessment"],
    riskLevel: "HIGH",
  },
  {
    number: 11,
    criterionNumber: 3,
    title: "Évaluation de l'atteinte des objectifs",
    shortDescription: "Mettre en place des évaluations adaptées aux objectifs visés.",
    expectedLevel: "Les évaluations démontrent l'atteinte ou non des objectifs annoncés.",
    evidenceExamples: ["Grille d'évaluation", "Quiz final", "Résultats d'évaluation"],
    applicableTo: ["training actions", "apprenticeship", "VAE", "skills assessment"],
    riskLevel: "CRITICAL",
  },
  {
    number: 12,
    criterionNumber: 3,
    title: "Engagement des bénéficiaires",
    shortDescription: "Prévenir les ruptures et soutenir l'assiduité ou la participation.",
    expectedLevel: "L'organisme suit l'engagement et trace les relances ou mesures prises.",
    evidenceExamples: ["Feuille d'émargement", "Relances d'absence", "Tableau de suivi"],
    applicableTo: ["training actions", "apprenticeship"],
    riskLevel: "MEDIUM",
  },
  {
    number: 13,
    criterionNumber: 3,
    title: "Coordination alternance",
    shortDescription: "Organiser la coordination avec l'entreprise pour les parcours en alternance.",
    expectedLevel: "Les échanges et responsabilités entre centre et entreprise sont tracés.",
    evidenceExamples: ["Livret d'alternance", "Compte rendu tuteur", "Planning de suivi"],
    applicableTo: ["apprenticeship"],
    riskLevel: "MEDIUM",
  },
  {
    number: 14,
    criterionNumber: 3,
    title: "Citoyenneté et obligations apprentis",
    shortDescription: "Informer les apprentis sur droits, devoirs, santé, sécurité et citoyenneté.",
    expectedLevel: "Les informations spécifiques aux apprentis sont remises et compréhensibles.",
    evidenceExamples: ["Livret apprenti", "Feuille d'émargement information", "Support santé sécurité"],
    applicableTo: ["apprenticeship"],
    riskLevel: "MEDIUM",
  },
  {
    number: 15,
    criterionNumber: 3,
    title: "Droits et devoirs des apprentis",
    shortDescription: "Formaliser les règles relatives au statut d'apprenti et au parcours.",
    expectedLevel: "Les apprentis disposent d'une information documentée sur leur statut et leurs recours.",
    evidenceExamples: ["Guide apprenti", "Règlement intérieur CFA", "Support d'accueil"],
    applicableTo: ["apprenticeship"],
    riskLevel: "LOW",
  },
  {
    number: 16,
    criterionNumber: 3,
    title: "Présentation des candidats VAE",
    shortDescription: "Accompagner les candidats VAE dans la constitution et la présentation du dossier.",
    expectedLevel: "Le candidat dispose d'un accompagnement tracé et de repères pour présenter ses acquis.",
    evidenceExamples: ["Planning VAE", "Grille d'accompagnement", "Compte rendu d'entretien"],
    applicableTo: ["VAE"],
    riskLevel: "MEDIUM",
  },
  {
    number: 17,
    criterionNumber: 4,
    title: "Moyens humains et techniques",
    shortDescription: "Mettre à disposition des moyens adaptés aux objectifs, publics et modalités.",
    expectedLevel: "Les ressources humaines, matérielles et techniques sont adaptées et disponibles.",
    evidenceExamples: ["Liste des moyens", "Contrat plateforme", "Plan de salle ou accès outil"],
    applicableTo: ["training actions", "apprenticeship", "VAE", "skills assessment"],
    riskLevel: "HIGH",
  },
  {
    number: 18,
    criterionNumber: 4,
    title: "Coordination des intervenants",
    shortDescription: "Coordonner les équipes, sous-traitants et parties prenantes de la prestation.",
    expectedLevel: "Les rôles, informations transmises et coordinations sont tracés.",
    evidenceExamples: ["Brief intervenant", "Contrat sous-traitant", "Compte rendu de coordination"],
    applicableTo: ["training actions", "apprenticeship", "VAE", "skills assessment", "subcontractor"],
    riskLevel: "HIGH",
  },
  {
    number: 19,
    criterionNumber: 4,
    title: "Ressources pédagogiques",
    shortDescription: "Fournir des supports et ressources utiles aux bénéficiaires.",
    expectedLevel: "Les ressources sont accessibles, adaptées et mises à jour lorsque nécessaire.",
    evidenceExamples: ["Support pédagogique", "Accès LMS ou drive", "Bibliographie"],
    applicableTo: ["training actions", "apprenticeship", "VAE", "skills assessment"],
    riskLevel: "MEDIUM",
  },
  {
    number: 20,
    criterionNumber: 4,
    title: "Personnel dédié à l'apprentissage",
    shortDescription: "Identifier les personnels chargés de l'accompagnement des apprentis.",
    expectedLevel: "Les fonctions de référent ou d'accompagnement sont nommées et connues.",
    evidenceExamples: ["Organigramme CFA", "Fiche mission référent", "Liste contacts apprentis"],
    applicableTo: ["apprenticeship"],
    riskLevel: "LOW",
  },
  {
    number: 21,
    criterionNumber: 5,
    title: "Compétences des intervenants",
    shortDescription: "Vérifier et tenir à jour les compétences des formateurs et intervenants.",
    expectedLevel: "Les compétences sont justifiées au regard des prestations assurées.",
    evidenceExamples: ["CV formateur", "Diplômes", "Références professionnelles"],
    applicableTo: ["training actions", "apprenticeship", "VAE", "skills assessment", "subcontractor"],
    riskLevel: "CRITICAL",
  },
  {
    number: 22,
    criterionNumber: 5,
    title: "Développement des compétences",
    shortDescription: "Organiser le maintien et le développement des compétences des intervenants.",
    expectedLevel: "Les besoins de montée en compétence sont identifiés et suivis.",
    evidenceExamples: ["Plan de développement", "Attestation de formation formateur", "Veille pédagogique"],
    applicableTo: ["training actions", "apprenticeship", "VAE", "skills assessment"],
    riskLevel: "MEDIUM",
  },
  {
    number: 23,
    criterionNumber: 6,
    title: "Veille légale et réglementaire",
    shortDescription: "Réaliser une veille sur les obligations liées à l'activité de formation.",
    expectedLevel: "La veille est organisée, analysée et utilisée lorsque des évolutions impactent l'activité.",
    evidenceExamples: ["Tableau de veille", "Abonnement newsletter", "Action issue de veille"],
    applicableTo: ["training actions", "apprenticeship", "VAE", "skills assessment"],
    riskLevel: "HIGH",
  },
  {
    number: 24,
    criterionNumber: 6,
    title: "Veille métiers et compétences",
    shortDescription: "Suivre les évolutions métiers, emplois et compétences des secteurs concernés.",
    expectedLevel: "Les évolutions pertinentes alimentent les contenus ou méthodes pédagogiques.",
    evidenceExamples: ["Sources de veille métier", "Compte rendu réseau professionnel", "Mise à jour programme"],
    applicableTo: ["training actions", "apprenticeship"],
    riskLevel: "MEDIUM",
  },
  {
    number: 25,
    criterionNumber: 6,
    title: "Veille pédagogique et technologique",
    shortDescription: "Suivre les innovations pédagogiques et techniques utiles aux prestations.",
    expectedLevel: "La veille débouche sur des décisions ou améliorations lorsque c'est pertinent.",
    evidenceExamples: ["Journal de veille", "Test d'outil", "Compte rendu expérimentation"],
    applicableTo: ["training actions", "apprenticeship", "VAE", "skills assessment"],
    riskLevel: "LOW",
  },
  {
    number: 26,
    criterionNumber: 6,
    title: "Handicap et accessibilité",
    shortDescription: "Identifier les besoins handicap et mobiliser les réseaux ou adaptations utiles.",
    expectedLevel: "Un référent ou processus permet de traiter les situations de handicap avec traçabilité.",
    evidenceExamples: ["Procédure handicap", "Liste partenaires", "Fiche adaptation"],
    applicableTo: ["training actions", "apprenticeship", "VAE", "skills assessment"],
    riskLevel: "CRITICAL",
  },
  {
    number: 27,
    criterionNumber: 6,
    title: "Maîtrise de la sous-traitance",
    shortDescription: "Contrôler les prestations confiées à des sous-traitants ou partenaires.",
    expectedLevel: "Les exigences qualité sont contractualisées, suivies et vérifiées.",
    evidenceExamples: ["Contrat sous-traitance", "Charte qualité", "Évaluation sous-traitant"],
    applicableTo: ["subcontractor", "training actions", "apprenticeship"],
    riskLevel: "HIGH",
  },
  {
    number: 28,
    criterionNumber: 6,
    title: "Périodes en entreprise",
    shortDescription: "Mobiliser le réseau socio-économique pour les périodes en entreprise.",
    expectedLevel: "Les périodes en entreprise sont préparées, suivies et exploitées.",
    evidenceExamples: ["Convention de stage", "Liste entreprises", "Compte rendu visite"],
    applicableTo: ["training actions", "apprenticeship"],
    riskLevel: "MEDIUM",
  },
  {
    number: 29,
    criterionNumber: 6,
    title: "Insertion professionnelle des apprentis",
    shortDescription: "Suivre les indicateurs d'insertion ou poursuite de parcours des apprentis.",
    expectedLevel: "Les données disponibles sont collectées et utilisées pour piloter l'offre.",
    evidenceExamples: ["Enquête insertion", "Tableau de suivi diplômés", "Bilan CFA"],
    applicableTo: ["apprenticeship"],
    riskLevel: "LOW",
  },
  {
    number: 30,
    criterionNumber: 7,
    title: "Traitement des aléas et réclamations",
    shortDescription: "Recueillir, traiter et tracer les réclamations, incidents ou difficultés.",
    expectedLevel: "Un processus permet de qualifier les aléas, répondre et décider d'actions si besoin.",
    evidenceExamples: ["Registre réclamations", "Procédure réclamation", "Réponse bénéficiaire"],
    applicableTo: ["training actions", "apprenticeship", "VAE", "skills assessment"],
    riskLevel: "CRITICAL",
  },
  {
    number: 31,
    criterionNumber: 7,
    title: "Recueil des appréciations",
    shortDescription: "Collecter les appréciations des bénéficiaires et parties prenantes.",
    expectedLevel: "Les avis sont recueillis, analysés et conservés selon une méthode définie.",
    evidenceExamples: ["Questionnaire satisfaction", "Synthèse avis", "Compte rendu financeur"],
    applicableTo: ["training actions", "apprenticeship", "VAE", "skills assessment"],
    riskLevel: "HIGH",
  },
  {
    number: 32,
    criterionNumber: 7,
    title: "Amélioration continue",
    shortDescription: "Mettre en oeuvre et suivre des actions d'amélioration à partir des constats.",
    expectedLevel: "Les analyses donnent lieu à un plan d'action suivi et réévalué.",
    evidenceExamples: ["Plan d'amélioration", "Revue qualité", "Bilan annuel"],
    applicableTo: ["training actions", "apprenticeship", "VAE", "skills assessment"],
    riskLevel: "CRITICAL",
  },
];

export const DEFAULT_RNQ_REFERENTIAL = {
  criteria: DEFAULT_RNQ_CRITERIA,
  indicators: DEFAULT_RNQ_INDICATORS,
} as const;
